<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>ProxyNodeHub</RootNamespace>
    <AssemblyName>ProxyNodeHub</AssemblyName>
    <Version>0.0.1</Version>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <!-- 自包含版 -->
  <PropertyGroup Condition="'$(SelfContained)' == 'true'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../core/ProxyNodeHub.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="logo.png" />
  </ItemGroup>

</Project>
